// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: h4YeDEMYgWVsBFTw8FMJtM
// Component: OSMs8QAIPT8r
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  useTrigger,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import Ratings from "../../Ratings" // plasmic-import: 3lGAJkj4nXZn/component
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css" // plasmic-import: h4YeDEMYgWVsBFTw8FMJtM/projectcss
import * as sty from "./PlasmicProductCard.module.css" // plasmic-import: OSMs8QAIPT8r/css
import ShoppingCartIcon from "./icons/PlasmicIcon__ShoppingCart" // plasmic-import: dyL6CJivfwG9/icon
import HeartOIcon from "./icons/PlasmicIcon__HeartO" // plasmic-import: zfCNI3XFkN_4/icon
import ExpandIcon from "./icons/PlasmicIcon__Expand" // plasmic-import: Z9cvjrMXgtPB/icon
import f1Ke0VtE63M3FX from "./images/f1.jpeg" // plasmic-import: Ke0VtE63M3fX/picture

export const PlasmicProductCard__VariantProps = new Array(
  "withReviews",
  "onSale"
)

export const PlasmicProductCard__ArgProps = new Array(
  "title",
  "price",
  "image",
  "ratings"
)

function PlasmicProductCard__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  const [isRootHover, triggerRootHoverProps] = useTrigger("useHover", {})
  const triggers = {
    hover_root: isRootHover,
  }

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root,
        {
          [sty.root__onSale]: hasVariant(variants, "onSale", "onSale"),
          [sty.root__withReviews]: hasVariant(
            variants,
            "withReviews",
            "withReviews"
          ),
        }
      )}
      data-plasmic-trigger-props={[triggerRootHoverProps]}
    >
      <div
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox__d0Elq
        )}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__f8QUr)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"none"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100%"}
              src={{
                src: f1Ke0VtE63M3FX,
                fullWidth: 270,
                fullHeight: 310,
                aspectRatio: undefined,
              }}
            />
          ),

          value: args.image,
        })}

        {(hasVariant(variants, "onSale", "onSale") ? true : true) ? (
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.freeBox___5JpEo,
              {
                [sty.freeBox__onSale___5JpEo8TZG]: hasVariant(
                  variants,
                  "onSale",
                  "onSale"
                ),
              }
            )}
          >
            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__crPq5
              )}
            >
              {"Sale"}
            </div>
          </div>
        ) : null}
        {(triggers.hover_root ? true : true) ? (
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.freeBox__zyfib
            )}
          >
            <ShoppingCartIcon
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.svg__kPb1R
              )}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__gixV
              )}
            >
              {"Add to cart"}
            </div>

            <HeartOIcon
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.svg__qdbKm
              )}
              role={"img"}
            />

            <ExpandIcon
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.svg__gpb33
              )}
              role={"img"}
            />
          </p.Stack>
        ) : null}
      </div>

      {(hasVariant(variants, "withReviews", "withReviews") ? true : true)
        ? p.renderPlasmicSlot({
            defaultContents: (
              <Ratings
                className={classNames("__wab_instance", sty.ratings__cfWxc)}
              />
            ),

            value: args.ratings,
          })
        : null}

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox__j8BA5
        )}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Title",
          value: args.title,
          className: classNames(sty.slotTargetTitle),
        })}

        {p.renderPlasmicSlot({
          defaultContents: "$100",
          value: args.price,
          className: classNames(sty.slotTargetPrice),
        })}
      </p.Stack>
    </p.Stack>
  )
}

const PlasmicDescendants = {
  root: ["root"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicProductCard__ArgProps,
      internalVariantPropNames: PlasmicProductCard__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicProductCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicProductCard"
  } else {
    func.displayName = `PlasmicProductCard.${nodeName}`
  }
  return func
}

export const PlasmicProductCard = Object.assign(
  // Top-level PlasmicProductCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicProductCard
    internalVariantProps: PlasmicProductCard__VariantProps,
    internalArgProps: PlasmicProductCard__ArgProps,
  }
)

export default PlasmicProductCard
/* prettier-ignore-end */
