// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: h4YeDEMYgWVsBFTw8FMJtM
// Component: 3lGAJkj4nXZn
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css" // plasmic-import: h4YeDEMYgWVsBFTw8FMJtM/projectcss
import * as sty from "./PlasmicRatings.module.css" // plasmic-import: 3lGAJkj4nXZn/css
import StarIcon from "./icons/PlasmicIcon__Star" // plasmic-import: TggKS6wlgmGZ/icon

export const PlasmicRatings__VariantProps = new Array("stars")

export const PlasmicRatings__ArgProps = new Array("numReviews")

function PlasmicRatings__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root,
        {
          [sty.root__stars_five]: hasVariant(variants, "stars", "five"),
          [sty.root__stars_four]: hasVariant(variants, "stars", "four"),
          [sty.root__stars_one]: hasVariant(variants, "stars", "one"),
          [sty.root__stars_three]: hasVariant(variants, "stars", "three"),
          [sty.root__stars_two]: hasVariant(variants, "stars", "two"),
          [sty.root__stars_zero]: hasVariant(variants, "stars", "zero"),
        }
      )}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(defaultcss.all, projectcss.all, sty.freeBox)}
      >
        {(hasVariant(variants, "stars", "zero") ? true : true) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__bspf,
              {
                [sty.svg__stars_five__bspfYtWGw]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_zero__bspfRiyNc]: hasVariant(
                  variants,
                  "stars",
                  "zero"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg___9SnEl,
              {
                [sty.svg__stars_five___9SnElYtWGw]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four___9SnElXtwsv]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                [sty.svg__stars_one___9SnELtUtfy]: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                [sty.svg__stars_three___9SnELgQqka]: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                [sty.svg__stars_two___9SnEl9Wk0N]: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                [sty.svg__stars_zero___9SnELriyNc]: hasVariant(
                  variants,
                  "stars",
                  "zero"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__lB12Y,
              {
                [sty.svg__stars_five__lB12YYtWGw]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four__lB12YXtwsv]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                [sty.svg__stars_one__lB12YtUtfy]: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                [sty.svg__stars_three__lB12YgQqka]: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                [sty.svg__stars_two__lB12Y9Wk0N]: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                [sty.svg__stars_zero__lB12YriyNc]: hasVariant(
                  variants,
                  "stars",
                  "zero"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg___7M3Ja,
              {
                [sty.svg__stars_five___7M3JaYtWGw]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four___7M3JaXtwsv]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                [sty.svg__stars_one___7M3JatUtfy]: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                [sty.svg__stars_three___7M3JagQqka]: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                [sty.svg__stars_two___7M3Ja9Wk0N]: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                [sty.svg__stars_zero___7M3JariyNc]: hasVariant(
                  variants,
                  "stars",
                  "zero"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__eMmbY,
              {
                [sty.svg__stars_five__eMmbYYtWGw]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four__eMmbYXtwsv]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                [sty.svg__stars_one__eMmbYtUtfy]: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                [sty.svg__stars_three__eMmbYgQqka]: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                [sty.svg__stars_two__eMmbY9Wk0N]: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                [sty.svg__stars_zero__eMmbYriyNc]: hasVariant(
                  variants,
                  "stars",
                  "zero"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? true
            : hasVariant(variants, "stars", "zero")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__dxRod,
              {
                [sty.svg__stars_five__dxRodYtWGw]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four__dxRodXtwsv]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                [sty.svg__stars_one__dxRodtUtfy]: hasVariant(
                  variants,
                  "stars",
                  "one"
                ),

                [sty.svg__stars_three__dxRodgQqka]: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                [sty.svg__stars_two__dxRod9Wk0N]: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),

                [sty.svg__stars_zero__dxRodriyNc]: hasVariant(
                  variants,
                  "stars",
                  "zero"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__f60V,
              {
                [sty.svg__stars_five__f60VYtWGw]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four__f60VXtwsv]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                [sty.svg__stars_three__f60VgQqka]: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),

                [sty.svg__stars_two__f60V9Wk0N]: hasVariant(
                  variants,
                  "stars",
                  "two"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__cpGJ,
              {
                [sty.svg__stars_five__cpGJYtWGw]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four__cpGJXtwsv]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),

                [sty.svg__stars_three__cpGJgQqka]: hasVariant(
                  variants,
                  "stars",
                  "three"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : true
        ) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__tSWhR,
              {
                [sty.svg__stars_five__tSWhRYtWGw]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),

                [sty.svg__stars_four__tSWhRXtwsv]: hasVariant(
                  variants,
                  "stars",
                  "four"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? true : true) ? (
          <StarIcon
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.svg__fVz,
              {
                [sty.svg__stars_five__fVzYtWGw]: hasVariant(
                  variants,
                  "stars",
                  "five"
                ),
              }
            )}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotTargetNumReviews),
      })}
    </p.Stack>
  )
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings"
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`
  }
  return func
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps,
  }
)

export default PlasmicRatings
/* prettier-ignore-end */
