// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: h4YeDEMYgWVsBFTw8FMJtM
// Component: 9ld2M9zaTnJ
import * as React from "react"
import { Link } from "gatsby"
import * as p from "@plasmicapp/react-web"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import IconLink from "../../IconLink" // plasmic-import: _XLNFD5jogvT/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen" // plasmic-import: JD6wF7zwyldn/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css" // plasmic-import: h4YeDEMYgWVsBFTw8FMJtM/projectcss
import * as sty from "./PlasmicFooter.module.css" // plasmic-import: 9ld2M9zaTnJ/css
import LocationArrowIcon from "./icons/PlasmicIcon__LocationArrow" // plasmic-import: _CApgrniFXIJ/icon
import FacebookIcon from "./icons/PlasmicIcon__Facebook" // plasmic-import: TqBbl-56ldVJ/icon
import InstagramIcon from "./icons/PlasmicIcon__Instagram" // plasmic-import: yXmXajoODEBB/icon
import LinkedinIcon from "./icons/PlasmicIcon__Linkedin" // plasmic-import: A8J_mw_aExJ_/icon

export const PlasmicFooter__VariantProps = new Array()

export const PlasmicFooter__ArgProps = new Array()

function PlasmicFooter__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants(),
  })

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox__y3RzK
        )}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__tEnGx
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__zZboQ
            )}
          >
            {"Information"}
          </div>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.freeBox__vuT70
            )}
          >
            <p.PlasmicLink
              className={classNames(
                defaultcss.a,
                projectcss.a,
                defaultcss.__wab_text,
                sty.link__dhezn
              )}
              component={Link}
              href={"#"}
              platform={"gatsby"}
            >
              {"About Us"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                defaultcss.a,
                projectcss.a,
                defaultcss.__wab_text,
                sty.link__ouIk1
              )}
              component={Link}
              href={"#"}
              platform={"gatsby"}
            >
              {"Contact Us"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                defaultcss.a,
                projectcss.a,
                defaultcss.__wab_text,
                sty.link___4J2Xh
              )}
              component={Link}
              href={"#"}
              platform={"gatsby"}
            >
              {"News"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                defaultcss.a,
                projectcss.a,
                defaultcss.__wab_text,
                sty.link__tgOyI
              )}
              component={Link}
              href={"#"}
              platform={"gatsby"}
            >
              {"Store"}
            </p.PlasmicLink>
          </p.Stack>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__bMhg
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__hc7HI
            )}
          >
            {"Collections"}
          </div>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.freeBox__fufv9
            )}
          >
            <p.PlasmicLink
              className={classNames(
                defaultcss.a,
                projectcss.a,
                defaultcss.__wab_text,
                sty.link__zFa7Y
              )}
              component={Link}
              href={"#"}
              platform={"gatsby"}
            >
              {"Wooden Chair"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                defaultcss.a,
                projectcss.a,
                defaultcss.__wab_text,
                sty.link__ujLZ
              )}
              component={Link}
              href={"#"}
              platform={"gatsby"}
            >
              {"Royal Cloth Sofa"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                defaultcss.a,
                projectcss.a,
                defaultcss.__wab_text,
                sty.link__mUblZ
              )}
              component={Link}
              href={"#"}
              platform={"gatsby"}
            >
              {"Accent Chair"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                defaultcss.a,
                projectcss.a,
                defaultcss.__wab_text,
                sty.link__vOlQe
              )}
              component={Link}
              href={"#"}
              platform={"gatsby"}
            >
              {"Bed"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                defaultcss.a,
                projectcss.a,
                defaultcss.__wab_text,
                sty.link__vzc8D
              )}
              component={Link}
              href={"#"}
              platform={"gatsby"}
            >
              {"Hanging Lamp"}
            </p.PlasmicLink>
          </p.Stack>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__ypJn
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__aqm7
            )}
          >
            {"My Accounts"}
          </div>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.freeBox__fd2Jv
            )}
          >
            <p.PlasmicLink
              className={classNames(
                defaultcss.a,
                projectcss.a,
                defaultcss.__wab_text,
                sty.link___7C3ET
              )}
              component={Link}
              href={"#"}
              platform={"gatsby"}
            >
              {"My Account"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                defaultcss.a,
                projectcss.a,
                defaultcss.__wab_text,
                sty.link__iAbFi
              )}
              component={Link}
              href={"#"}
              platform={"gatsby"}
            >
              {"Wishlist"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                defaultcss.a,
                projectcss.a,
                defaultcss.__wab_text,
                sty.link__duvsG
              )}
              component={Link}
              href={"#"}
              platform={"gatsby"}
            >
              {"Community"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                defaultcss.a,
                projectcss.a,
                defaultcss.__wab_text,
                sty.link__mP6Mc
              )}
              component={Link}
              href={"#"}
              platform={"gatsby"}
            >
              {"Order History"}
            </p.PlasmicLink>

            <p.PlasmicLink
              className={classNames(
                defaultcss.a,
                projectcss.a,
                defaultcss.__wab_text,
                sty.link__xBjmq
              )}
              component={Link}
              href={"#"}
              platform={"gatsby"}
            >
              {"My Cart"}
            </p.PlasmicLink>
          </p.Stack>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__ouNIq
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__vflf1
            )}
          >
            {"Newsletter"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__snIzG
            )}
          >
            {"Subscribe to get latest news, updates, and information"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.freeBox__ffdVv
            )}
          >
            <input
              data-plasmic-name={"textInput"}
              data-plasmic-override={overrides.textInput ?? overrides.textbox}
              className={classNames(
                defaultcss.input,
                projectcss.input,
                sty.textInput
              )}
              placeholder={"Enter Email Here..."}
              size={1}
              type={"text"}
              value={""}
            />

            <button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames(
                defaultcss.button,
                projectcss.button,
                sty.button
              )}
            >
              <LocationArrowIcon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__t6Nb
                )}
                role={"img"}
              />
            </button>
          </div>
        </p.Stack>
      </p.Stack>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(
          defaultcss.all,
          projectcss.all,
          sty.freeBox__jm2Vi
        )}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox___3Gqp9
          )}
        >
          <IconLink
            className={classNames("__wab_instance", sty.iconLink__mNwc)}
            icon={
              <FacebookIcon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg___24BR
                )}
                role={"img"}
              />
            }
          />

          <IconLink
            className={classNames("__wab_instance", sty.iconLink__k2L9A)}
            icon={
              <InstagramIcon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__dWDsX
                )}
                role={"img"}
              />
            }
          />

          <IconLink
            className={classNames("__wab_instance", sty.iconLink___4BjPu)}
            icon={
              <LinkedinIcon
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.svg__qa1Id
                )}
                role={"img"}
              />
            }
          />
        </p.Stack>

        <div
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__qkY7
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              defaultcss.__wab_text,
              sty.text__cI1Kb
            )}
          >
            {"© Copyright. "}
          </div>

          <p.PlasmicLink
            className={classNames(
              defaultcss.a,
              projectcss.a,
              defaultcss.__wab_text,
              sty.link__qkKkl
            )}
            component={Link}
            href={"https://www.plasmic.app/"}
            platform={"gatsby"}
          >
            {"Made by Plasmic. "}
          </p.PlasmicLink>

          <p.PlasmicLink
            className={classNames(
              defaultcss.a,
              projectcss.a,
              defaultcss.__wab_text,
              sty.link__pdFDm
            )}
            component={Link}
            href={"https://www.themesine.com/"}
            platform={"gatsby"}
          >
            {"Inspired by Themesine."}
          </p.PlasmicLink>
        </div>
      </p.Stack>
    </div>
  )
}

const PlasmicDescendants = {
  root: ["root", "textInput", "button"],
  textInput: ["textInput"],
  button: ["button"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooter__ArgProps,
      internalVariantPropNames: PlasmicFooter__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicFooter"
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`
  }
  return func
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textInput: makeNodeComponent("textInput"),
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps,
  }
)

export default PlasmicFooter
/* prettier-ignore-end */
