// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: h4YeDEMYgWVsBFTw8FMJtM
// Component: tHsFK95hfmH
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import Header from "../../Header" // plasmic-import: 6szZRisEj_D/component
import ProductCarousel from "../../ProductCarousel" // plasmic-import: YL7BR56HsPOa/component
import ProductCard from "../../ProductCard" // plasmic-import: OSMs8QAIPT8r/component
import Ratings from "../../Ratings" // plasmic-import: 3lGAJkj4nXZn/component
import FeatureItem from "../../FeatureItem" // plasmic-import: 0LPtouwpT9T/component
import BlogPost from "../../BlogPost" // plasmic-import: Y3Zl51ohjoWx/component
import Footer from "../../Footer" // plasmic-import: 9ld2M9zaTnJ/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen" // plasmic-import: JD6wF7zwyldn/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as defaultcss from "../plasmic__default_style.module.css" // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css" // plasmic-import: h4YeDEMYgWVsBFTw8FMJtM/projectcss
import * as sty from "./PlasmicHome.module.css" // plasmic-import: tHsFK95hfmH/css
import arrivals12Rz9AOeGfEei from "./images/arrivals1.png" // plasmic-import: 2rz9aOeGfEEI/picture
import arrivals2ZqO0RuyvVLrh from "./images/arrivals2.png" // plasmic-import: ZqO0RuyvVLrh/picture
import arrivals39MztNLcHt9Rb from "./images/arrivals3.png" // plasmic-import: 9mztNLcHt9RB/picture
import arrivals4NCztqkrjstbo from "./images/arrivals4.png" // plasmic-import: NCztqkrjstbo/picture
import arrivals5Mv6TW3SHoOz from "./images/arrivals5.png" // plasmic-import: MV6tW3SHo_OZ/picture
import arrivals6ZNkObeSz3DHy from "./images/arrivals6.png" // plasmic-import: zNKObeSZ3dHY/picture
import arrivals7Hzg5Pr1SU3Jw from "./images/arrivals7.png" // plasmic-import: Hzg5PR1sU3Jw/picture
import arrivals8Tn4JcvNZlcPl from "./images/arrivals8.png" // plasmic-import: tn4JcvNZlcPL/picture
import f2Nwhlme3Uhp4 from "./images/f2.jpeg" // plasmic-import: Nwhlme_3Uhp4/picture
import f3NpR1JFx7HfBn from "./images/f3.jpeg" // plasmic-import: npR1jFX7HFBn/picture
import f4MB2Bad79Kb from "./images/f4.jpeg" // plasmic-import: M_b_2BAD79Kb/picture
import b1K27HoFu3N4Re from "./images/b1.jpeg" // plasmic-import: k27HoFu3N4re/picture
import b2O7Pftgdik2Se from "./images/b2.jpeg" // plasmic-import: o7pftgdik2se/picture
import b3JkeOYkN6M5Aa from "./images/b3.jpeg" // plasmic-import: jkeOYkN6M5Aa/picture
import adidasCb8LnqYtLnU from "./images/adidas.png" // plasmic-import: Cb8LnqYtLn_U/picture
import hmFZj1KzvOlc from "./images/hm.png" // plasmic-import: f-zj1KzvOLC_/picture
import kappaXXpEs7CG2Wf from "./images/kappa.png" // plasmic-import: xXPEs7C-G2Wf/picture
import lacosteTNcMhjKz6HFz from "./images/lacoste.png" // plasmic-import: TNcMHJKz6HFz/picture
import levisIbSGbnaNdGti from "./images/levis.png" // plasmic-import: IbSGbnaNDGti/picture

export const PlasmicHome__VariantProps = new Array()

export const PlasmicHome__ArgProps = new Array()

function PlasmicHome__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants(),
  })

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.freeBox__jog0S
            )}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox__fAfpk
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox__z2A3
                )}
              >
                <Header
                  data-plasmic-name={"header"}
                  data-plasmic-override={overrides.header}
                />

                <ProductCarousel
                  data-plasmic-name={"productCarousel"}
                  data-plasmic-override={overrides.productCarousel}
                  className={classNames("__wab_instance", sty.productCarousel)}
                />
              </div>
            </p.Stack>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox__g5HFs
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__jdUlQ
                )}
              >
                {"New Arrivals"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.columns__ddAb5
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__u7Dz
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__j6O9U
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__vdzVj)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals12Rz9AOeGfEei,
                        fullWidth: 120,
                        fullHeight: 120,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$65.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__cs9ZD
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Wooden Chair"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__lamCv
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__hRGew
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__fdryO)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals2ZqO0RuyvVLrh,
                        fullWidth: 138,
                        fullHeight: 116,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$80.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__yug9J
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Single Armchair"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__btGlx
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___1VJxb
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__hL0U1)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals39MztNLcHt9Rb,
                        fullWidth: 135,
                        fullHeight: 116,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$40.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__xChXs
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Wooden Armchair"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__sIeIs
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___8YXvb
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___00Uc4)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals4NCztqkrjstbo,
                        fullWidth: 100,
                        fullHeight: 130,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__oEuDr
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Stylish Chair"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__epwLz
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__rKmk
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__f49P)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals5Mv6TW3SHoOz,
                        fullWidth: 105,
                        fullHeight: 127,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$120.00"}
                  title={"Modern Chair"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__kgOpz
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__lsc7R
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__hbtp9)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals6ZNkObeSz3DHy,
                        fullWidth: 176,
                        fullHeight: 123,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$140.00"}
                  title={"Mapple Wood Dinning Table"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__xoR8H
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__k9Awp
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__p5X9T)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals7Hzg5Pr1SU3Jw,
                        fullWidth: 160,
                        fullHeight: 120,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  onSale={"onSale"}
                  price={"$90.00"}
                  title={"Arm Chair"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__rpHTl
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__zjKaz
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__pc1Or)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"160px"}
                      src={{
                        src: arrivals8Tn4JcvNZlcPl,
                        fullWidth: 191,
                        fullHeight: 101,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$140.00"}
                  title={
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        defaultcss.__wab_text,
                        sty.text__cRlu7
                      )}
                    >
                      {"Wooden Bed"}
                    </div>
                  }
                />
              </div>
            </p.Stack>

            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox__dQtp6
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text___2O7Bg
                )}
              >
                {"Featured Products"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.columns__emAOb
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__g52Nv
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__h8J1
                  )}
                  price={
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        defaultcss.__wab_text,
                        sty.text__sxYs8
                      )}
                    >
                      {"$160.00"}
                    </div>
                  }
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__eZto1
                      )}
                      numReviews={"(12 Review)"}
                      stars={"two"}
                    />
                  }
                  title={
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        defaultcss.__wab_text,
                        sty.text__zNvz
                      )}
                    >
                      {"Designed Sofa"}
                    </div>
                  }
                  withReviews={"withReviews"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__me14R
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__frgLh
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__u2T6P)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f2Nwhlme3Uhp4,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$200.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__sYd4T
                      )}
                      stars={"four"}
                    />
                  }
                  title={"Dining Table"}
                  withReviews={"withReviews"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__fplCp
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__aSaQ
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ecf53)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f3NpR1JFx7HfBn,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__o1Jam
                      )}
                      numReviews={"(23 Review)"}
                      stars={"five"}
                    />
                  }
                  title={"Chair and Table"}
                  withReviews={"withReviews"}
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__bdwD
                )}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__cPrAn
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__yhP4)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: f4MB2Bad79Kb,
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                  price={"$299.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__hozfO
                      )}
                      numReviews={"(35 Review)"}
                    />
                  }
                  title={"Modern Arm Chair"}
                  withReviews={"withReviews"}
                />
              </div>
            </p.Stack>

            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox__b7Oq7
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  defaultcss.__wab_text,
                  sty.text__mSzT1
                )}
              >
                {"Latest Blog"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.columns__a7Njo
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__giOv
                )}
              >
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__x1UOu)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__lXIzC)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b1K27HoFu3N4Re,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__o8B1I
                )}
              >
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost___79XzV)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__huVkH)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b2O7Pftgdik2Se,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                />
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column___8Ymui
                )}
              >
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__cobx)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__e3DLm)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: b3JkeOYkN6M5Aa,
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined,
                      }}
                    />
                  }
                />
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox___3GogA
              )}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__zy0KS)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"90px"}
                src={{
                  src: adidasCb8LnqYtLnU,
                  fullWidth: 90,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__lVg0R)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"91px"}
                src={{
                  src: hmFZj1KzvOlc,
                  fullWidth: 91,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__ppxZy)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"98px"}
                src={{
                  src: kappaXXpEs7CG2Wf,
                  fullWidth: 98,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__qbQ6E)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"124px"}
                src={{
                  src: lacosteTNcMhjKz6HFz,
                  fullWidth: 124,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__cuOfK)}
                displayHeight={"60px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"125px"}
                src={{
                  src: levisIbSGbnaNdGti,
                  fullWidth: 125,
                  fullHeight: 60,
                  aspectRatio: undefined,
                }}
              />
            </p.Stack>

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  )
}

const PlasmicDescendants = {
  root: ["root", "header", "productCarousel", "featureItem", "footer"],
  header: ["header"],
  productCarousel: ["productCarousel"],
  featureItem: ["featureItem"],
  footer: ["footer"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps,
    })

    const { dataFetches } = props
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicHome"
  } else {
    func.displayName = `PlasmicHome.${nodeName}`
  }
  return func
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    productCarousel: makeNodeComponent("productCarousel"),
    featureItem: makeNodeComponent("featureItem"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,
  }
)

export default PlasmicHome
/* prettier-ignore-end */
